#!/usr/bin/env python
# /* -*- Mode: Python; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

import argparse

# ROS imports ############################
import roslib; roslib.load_manifest('vros_display')
import rospy
from geometry_msgs.msg import Pose2D
from  sensor_msgs.msg import Joy

import vros_display.srv
import display_client
##########################################
import os
import numpy as np

def gain_func( x ):
    return (2.0 * x)**3.0

class App:
    def __init__(self):
        rospy.init_node('joystick_cursor')

        display_server = display_client.DisplayServerProxy()
        display_server.enter_standby_mode()
        display_server.set_mode('Stimulus2DSprite')
        self.pub = rospy.Publisher('sprite_pose', Pose2D)
        joy_sub = rospy.Subscriber("joy", Joy, self.joy_callback)

        self.cur_joy_x = 0
        self.cur_joy_y = 0

        self.x = 100
        self.y = 100

    def joy_callback(self, msg):
        self.cur_joy_x = msg.axes[0]
        self.cur_joy_y = msg.axes[1]

        if msg.buttons[0]:
            print '%.1f %.1f'%(self.x, self.y)
        
    def run(self):
        while not rospy.is_shutdown():

            self.x -= gain_func( self.cur_joy_x )
            self.y -= gain_func( self.cur_joy_y )

            pose2d = Pose2D()
            pose2d.x=self.x
            pose2d.y=self.y
            pose2d.theta = 0.0
            self.pub.publish(pose2d)

            rospy.sleep(0.1)

def main():
    parser = argparse.ArgumentParser()
    # use argparse, but only after ROS did its thing
    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    app = App()
	app.run()

if __name__=='__main__':
    main()
