#!/usr/bin/env python
# /* -*- Mode: Python; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

import roslib; roslib.load_manifest('vros_display')
import rospy

from geometry_msgs.msg import Pose2D
from  sensor_msgs.msg import Joy
import vros_display.srv

import display_client

import os
import numpy as np
import argparse

class App:
    def __init__(self):
        rospy.init_node('joystick_cursor')

        self.display_server = display_client.DisplayServerProxy()
        self.old_mode = self.display_server.get_mode()
        self.display_server.set_mode('Stimulus2DSprite')

        self.pub = rospy.Publisher('sprite_pose', Pose2D)
        self.pubclick = rospy.Publisher('joy_click_pose', Pose2D)
        joy_sub = rospy.Subscriber('joy', Joy, self.joy_callback)

        self.cur_joy_x = 0
        self.cur_joy_y = 0

        self.x = 100
        self.y = 100

        self._gain_k = rospy.get_param('~gain_k', 2.0)
        self._gain_p = rospy.get_param('~gain_p', 3.0)

    def _gain_func(self, x):
        return (self._gain_k * x)**self._gain_p

    def joy_callback(self, msg):
        self.cur_joy_x = msg.axes[0]
        self.cur_joy_y = msg.axes[1]

        if msg.buttons[0]:
            print '%.1f %.1f'%(self.x, self.y)
            self.pubclick.publish(
                            Pose2D(float(self.x), float(self.y), 0.0))
        
    def run(self):
        while not rospy.is_shutdown():
            self.x -= self._gain_func( self.cur_joy_x )
            self.y -= self._gain_func( self.cur_joy_y )

            pose2d = Pose2D()
            pose2d.x=self.x
            pose2d.y=self.y
            pose2d.theta = 0.0
            self.pub.publish(pose2d)

            rospy.sleep(0.1)

        self.display_server.set_mode(self.old_mode)

def main():
    parser = argparse.ArgumentParser()
    # use argparse, but only after ROS did its thing
    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    app = App()
	app.run()

if __name__=='__main__':
    main()
