#!/usr/bin/env python
import roslib; roslib.load_manifest('vros_display')
import rospy
from geometry_msgs.msg import Pose
import tf.transformations
import numpy as np

def talker():
    pub = rospy.Publisher('pose', Pose)
    rospy.init_node('talker')
    while not rospy.is_shutdown():
        t = rospy.get_time()
        x=0;z=0
        x = 10*np.sin( t*2*np.pi/5.0 )
        #y = 0.4*np.cos( t*2*np.pi/15.0 )
        y = 0
        z = 0.4*np.cos( t*2*np.pi/15.0 ) + 0.5
        msg = Pose()
        msg.position.x=x
        msg.position.y=y
        msg.position.z=z

        theta = (t*2*np.pi / 17.0) % (2*np.pi)
        quat = tf.transformations.quaternion_about_axis(  theta, (0,0,1) )
        for i in range(4):
            setattr(msg.orientation,'xyzw'[i], quat[i])

        pub.publish(msg)
        rospy.sleep(0.01)

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException: pass
