# these are hacks for now...
SET(CUDA_TOOLKIT_ROOT "/opt/cuda-5.0")

# this shouldn't be too hacky below here
SET(OSG_COMPUTE_INCLUDE_PATHS
  "${CUDA_TOOLKIT_ROOT}/include")

FIND_LIBRARY(OSG_COMPUTE_LIBRARY
  NAMES osgCompute
  PATHS ${OSG_COMPUTE_LIBRARY_PATHS})

FIND_LIBRARY(OSG_CUDA_LIBRARY
  NAMES osgCuda
  PATHS ${OSG_COMPUTE_LIBRARY_PATHS})

FIND_LIBRARY(OSG_CUDA_INIT_LIBRARY
  NAMES osgCudaInit
  PATHS ${OSG_COMPUTE_LIBRARY_PATHS})

FIND_LIBRARY(OSG_CUDA_UTIL_LIBRARY
  NAMES osgCudaUtil
  PATHS ${OSG_COMPUTE_LIBRARY_PATHS})

FIND_LIBRARY(OSG_CUDA_STATS_LIBRARY
  NAMES osgCudaStats
  PATHS ${OSG_COMPUTE_LIBRARY_PATHS})
  
SET(OSG_COMPUTE_LIBRARIES ${OSG_COMPUTE_LIBRARY} ${OSG_CUDA_LIBRARY}
  ${OSG_CUDA_INIT_LIBRARY} ${OSG_CUDA_STATS_LIBRARY}
  ${OSG_CUDA_UTIL_LIBRARY})
