#!/usr/bin/env python
import numpy as np
import argparse
import json

import roslib; roslib.load_manifest('freemoovr_engine')
import rospy
import freemoovr_engine.display_client as display_client
from std_msgs.msg import String


def switch_calibration(period):
    filename_pub = rospy.Publisher('p2g_calibration_filename', String)
    geom_json_buf_pub = rospy.Publisher('geom_json_buf', String)
    geom_buf1 = json.dumps({"model": "cylinder",
                            "base": {"y": 0.0, "x": 0.0, "z": 0.0},
                            "radius": 0.046,
                            "axis": {"y": 0.0, "x": 0.0, "z": 0.144}})
    geom_buf2 = json.dumps({'model': 'from_file',
                            'filename': '$(find freemoovr_engine)/data/flycube.osg'})
    filename_and_geom_list = [('$(find freemoovr_engine)/config/p2g.exr',geom_buf1),
                              ('$(find freemoovr_engine)/data/monitor_1920x1080.exr',geom_buf2)
                             ]
    current_index = 0
    while not rospy.is_shutdown():
        t = rospy.get_time()

        filename, geom_json_buf = filename_and_geom_list[current_index]
        filename_pub.publish(String(filename))
        geom_json_buf_pub.publish(String(geom_json_buf))
        rospy.sleep(period)
        current_index = (current_index+1)%len(filename_and_geom_list)

if __name__ == '__main__':
    rospy.init_node('demo_switch_calibration')

    parser = argparse.ArgumentParser()
    parser.add_argument('--period', type=float, help='period at which to switch calibration (default: 5)', default=5)

    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    switch_calibration(period=args.period)
