#!/usr/bin/env python
from __future__ import print_function
import argparse

import roslib; roslib.load_manifest('flyvr')
import rospy

import flyvr.srv

if __name__ == '__main__':
    rospy.init_node('drive_extrinsic_display_calibration_save_exr')

    parser = argparse.ArgumentParser()
    parser.add_argument('--fname', type=str, default='cal.exr',
                        help='filename of calibration.exr file')
    parser.add_argument('--service_name', type=str,
                        default='/drive_extrinsic_display_calibration/save_exr')
    argv = rospy.myargv()
    args = parser.parse_args(argv[1:])

    srv_proxy = rospy.ServiceProxy(args.service_name,
                                   flyvr.srv.SaveEXR)
    result = srv_proxy(args.fname)

    print( 'success: %s, saved to %r'%(result.success, result.fullpath ))
