name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  focal:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y python3-dev libopenscenegraph-dev python3-setuptools python3-numpy build-essential libjansson-dev cython3
    - name: Build
      run: python3 setup.py build
    - name: Install
      run: sudo python3 setup.py install
